### ISSUE TITLE
ООО Стратегия Риска

### ISSUE THREAD

**Issue by Malysh-ok** [Dvurechensky-Test-Tasks/RiskStrategyTask#1]
Дружище, почему ты написал в ReadMe фразу "SCAM-мошенническая компания"?

**Comment by Dvurechensky** [comment]
Привет! Я хотел работать, и получать от работы удовольствие. Разочаровался в компании! Потому что меня отфуболили с фразой ты написал слишком сложно, когда было сделано всё от и до, даже больше чем хотелось. Никто не устанавливал уровень сложности, мы не на рынке. Установлено техническое задание. Что такое мошенник - тот кто получает то, что ему необходимо обманным путём, работа которая была проделана может быть пущена в продакшен прямо сейчас - у меня большие знания о развитии и выпуске проектов, поднятии серверов и в целом о том, как работает крупный агрегатор или средний IT комплекс, ежу понятно что тут происходит. Все пункты задания были выполнены, вообще все. А мне рассказали за несуществующие аспекты, которых в задании не было, а именно какая-то более сложная поддержка не устроила, что абсурд. В то время, как я упростил работу системы в трое, сделав возможности для более удобной верстки Web части системы, используя обычный официальный GRUNT я написал на том языке который удобнее, но при этом сохранил требования задания в виде js и усилил надежность работы сервера минимизировав эти файлы (если что это сам браузер делает когда мы грузим любую страничку и это необходимо делать самому, если человек знаком со словом "оптимизация"). Все остальные технологии в проекте были строго по заданию, MVC, нужные версии, Entity, дизайн, события на дизайне. А вот чего не было, дак это описания какая кнопка за что должна отвечать, как должно работать проявление тех или иных событий, что повлекло за собой слепое поднятие swagger, для тестирования событий элементов управления. Когда программист видит такой ответ ничем кроме мошенничеством и отсутствием здравого смысла тут не пахнет, что в свою очередь и указано в заголовке README. Более того, ни одни правила не запрещают человеку складывать определённое мнение о потраченном им времени, потому что его время принадлежит ему и только ему, кто бы что не говорил. И у меня это время отобрала ваша компания.
